pub const CMD_AUTH_LOGON_CHALLENGE: u8 = 0x00;
pub const CMD_AUTH_LOGON_PROOF: u8 = 0x01;
pub const CMD_AUTH_RECONNECT_CHALLENGE: u8 = 0x02;
pub const CMD_AUTH_RECONNECT_PROOF: u8 = 0x03;
pub const CMD_REALM_LIST: u8 = 0x10;
